# Core system event types

ENTRY_ATTEMPT = "ENTRY_ATTEMPT"
ENTRY_APPROVED = "ENTRY_APPROVED"
ENTRY_BLOCKED = "ENTRY_BLOCKED"
EXIT = "EXIT"
KILL_SWITCH = "KILL_SWITCH"
SYSTEM_START = "SYSTEM_START"
SYSTEM_STOP = "SYSTEM_STOP"

Define core event types
